### PR TITLE
Drop `laminas/laminas-zendframework-bridge` and `zendframework/*` compatibility

### PR DESCRIPTION
**Pull request by PowerKiKi**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Increase performance by removing a compatibility layer while **not** introducing breaking changes.

This follow the process described in details in:

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-08-02-TSC-Minutes.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages

### CODE REVIEW

**Comment by Ocramius** [comment]
Hmm, I think we should put this to `3.4.x`, but default branch doesn't exist: lemme create one.

**Comment by Ocramius** [comment]
uh-oh, unsure if this will go smoothly that way.

We can try a rebase on `3.4.x`, or we can say this will only be in `4.0.x` :thinking:

**Comment by PowerKiKi** [comment]
I recreated the commit from scratch on branch 3.4

**Review by Ocramius — APPROVED** [review]
IMO looks good: wondering what to do about the CI failures, but IMO that's on @laminas side to fix :thinking:

**Comment by PowerKiKi** [comment]
I agree on the CI side. Strangely branch 4 had no CI at all :woman_shrugging:

**Review by Ocramius — APPROVED** [review]
I just had to adjust dependencies here: once upgrades were in place, all CI jobs were running just fine :-) 

:ship: thanks @PowerKiKi!

**Pull request merged**
