### PR TITLE
Psalm integration

### LINKED ISSUE #10: Psalm integration
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `.psalm.xml.dist` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description
- [x] Create psalm.xml.dist
- [x] Require vimeo/psalm
- [x] Create psalm-baseline.xml
- [x] Require psalm/plugin-phpunit
- [x] Upgrade phpunit/phpunit ^9.5
- [x] Add static-analysis composer script
- [x] Normalize composer.json
- [x] Update composer.lock

Fixes #10

### CODE REVIEW

**Comment by froschdesign** [comment]
@ghostwriter 
> Normalize composer.json

Can you tell me on what basis this was done? Thanks!

**Comment by ghostwriter** [comment]
@froschdesign (QA) To help us keep our `composer.json` nice and tidy, so we do not have to worry about it's structure and or formatting.

- restructure `composer.json` according to the underlying [JSON schema](https://getcomposer.org/schema.json). 
- sort entries in the `bin` section (by value)
- sort entries in the `config`, `extra`, and `scripts-descriptions` sections (by key)
- sort entries in the `conflict`, `provide`, `replace`, `require`, `require-dev`, and `suggest` sections (as you are used to from the [sort-packages ](https://getcomposer.org/doc/06-config.md#sort-packages) configuration)
- normalize version constraints in `conflict`, `provide`, `replace`, `require`, and `require-dev` sections

[Read more](https://localheinz.com/blog/2018/01/15/normalizing-composer.json/)

**Comment by froschdesign** [comment]
@ghostwriter 
I know the idea behind the normalization and also the Composer plugin but I don't know that we use this everywhere. So I assume it's a suggestion from you.

**Comment by ghostwriter** [comment]
@froschdesign Yes, that is correct. (hoping RFC wasn’t required)

**Comment by ghostwriter** [comment]
@froschdesign Yes, that is correct. (hopefully a RFC wasn’t required)

- Used in most, if not all, PRs that I submit, that touch `composer.json` file
- Would like to see it added to the `QA Checks`

**Comment by froschdesign** [comment]
@ghostwriter 
> hopefully a RFC wasn’t required

The problem is that inconsistencies arise between the repositories which can be result in more work or other problems. And with more than 180 repositories in 3 different GitHub organizations, nobody needs that.

> * Would like to see it added to the `QA Checks`

Please open an issue report at https://github.com/laminas/laminas-continuous-integration-action
Thanks in advance! 👍

**Comment by ghostwriter** [comment]
@froschdesign That is not a problem at all. 

I will take care of the PRs for all 3 orgs and send a PR to `laminas/laminas-continuous-integration-action` adding `ergebnis/composer-normalize` to the QA/CI process.

It can, and will, be consistent going forward.

**Comment by ghostwriter** [comment]
@froschdesign Reverted the last 2 commits in favor of #17

**Review by Ocramius — APPROVED** [review]
Rebased and updated dependencies (and baseline) accordingly.

Thanks @ghostwriter!

**Pull request merged**
